apiVersion: v1
kind: Service
metadata:
  name: do-uno-api
  namespace: do-uno
  labels:
    app: do-uno-api
spec:
  type: ClusterIP
  selector:
    app: do-uno-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
